/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface SignedDelegation {
    signature: string;
    delegation: {
        pubkey: string;
        targets?: Array<string>;
        expiration: string;
    };
}
export interface DelegationChain {
    publicKey: string;
    delegations: Array<SignedDelegation>;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface backendInterface {
    get_delegation(uuid: string): Promise<DelegationChain | null>;
    lookup_code(code: string): Promise<string | null>;
    register(uuid: string, public_key: string): Promise<RegisterResult>;
    store_delegation(code: string, chain: DelegationChain): Promise<void>;
    whoami(): Promise<Principal>;
}
import type { DelegationChain as _DelegationChain, RegisterResult as _RegisterResult, SignedDelegation as _SignedDelegation } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_delegation(arg0: string): Promise<DelegationChain | null> {
        const result = await this.actor.get_delegation(arg0);
        return from_candid_opt_n1(result);
    }
    async lookup_code(arg0: string): Promise<string | null> {
        const result = await this.actor.lookup_code(arg0);
        return from_candid_opt_n9(result);
    }
    async register(arg0: string, arg1: string): Promise<RegisterResult> {
        const result = await this.actor.register(arg0, arg1);
        return from_candid_RegisterResult_n10(result);
    }
    async store_delegation(arg0: string, arg1: DelegationChain): Promise<void> {
        const result = await this.actor.store_delegation(arg0, to_candid_DelegationChain_n12(arg1));
        return result;
    }
    async whoami(): Promise<Principal> {
        const result = await this.actor.whoami();
        return result;
    }
}
function from_candid_DelegationChain_n2(value: _DelegationChain): DelegationChain {
    return from_candid_record_n3(value);
}
function from_candid_RegisterResult_n10(value: _RegisterResult): RegisterResult {
    return from_candid_variant_n11(value);
}
function from_candid_SignedDelegation_n5(value: _SignedDelegation): SignedDelegation {
    return from_candid_record_n6(value);
}
function from_candid_opt_n1(value: [] | [_DelegationChain]): DelegationChain | null {
    return value.length === 0 ? null : from_candid_DelegationChain_n2(value[0]);
}
function from_candid_opt_n8(value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(value: {
    publicKey: string;
    delegations: Array<_SignedDelegation>;
}): {
    publicKey: string;
    delegations: Array<SignedDelegation>;
} {
    return {
        publicKey: value.publicKey,
        delegations: from_candid_vec_n4(value.delegations)
    };
}
function from_candid_record_n6(value: {
    signature: string;
    delegation: {
        pubkey: string;
        targets: [] | [Array<string>];
        expiration: string;
    };
}): {
    signature: string;
    delegation: {
        pubkey: string;
        targets?: Array<string>;
        expiration: string;
    };
} {
    return {
        signature: value.signature,
        delegation: from_candid_record_n7(value.delegation)
    };
}
function from_candid_record_n7(value: {
    pubkey: string;
    targets: [] | [Array<string>];
    expiration: string;
}): {
    pubkey: string;
    targets?: Array<string>;
    expiration: string;
} {
    return {
        pubkey: value.pubkey,
        targets: record_opt_to_undefined(from_candid_opt_n8(value.targets)),
        expiration: value.expiration
    };
}
function from_candid_variant_n11(value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n4(value: Array<_SignedDelegation>): Array<SignedDelegation> {
    return value.map((x)=>from_candid_SignedDelegation_n5(x));
}
function to_candid_DelegationChain_n12(value: DelegationChain): _DelegationChain {
    return to_candid_record_n13(value);
}
function to_candid_SignedDelegation_n15(value: SignedDelegation): _SignedDelegation {
    return to_candid_record_n16(value);
}
function to_candid_record_n13(value: {
    publicKey: string;
    delegations: Array<SignedDelegation>;
}): {
    publicKey: string;
    delegations: Array<_SignedDelegation>;
} {
    return {
        publicKey: value.publicKey,
        delegations: to_candid_vec_n14(value.delegations)
    };
}
function to_candid_record_n16(value: {
    signature: string;
    delegation: {
        pubkey: string;
        targets?: Array<string>;
        expiration: string;
    };
}): {
    signature: string;
    delegation: {
        pubkey: string;
        targets: [] | [Array<string>];
        expiration: string;
    };
} {
    return {
        signature: value.signature,
        delegation: to_candid_record_n17(value.delegation)
    };
}
function to_candid_record_n17(value: {
    pubkey: string;
    targets?: Array<string>;
    expiration: string;
}): {
    pubkey: string;
    targets: [] | [Array<string>];
    expiration: string;
} {
    return {
        pubkey: value.pubkey,
        targets: value.targets ? candid_some(value.targets) : candid_none(),
        expiration: value.expiration
    };
}
function to_candid_vec_n14(value: Array<SignedDelegation>): Array<_SignedDelegation> {
    return value.map((x)=>to_candid_SignedDelegation_n15(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
