/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const SignedDelegation = IDL.Record({
    'signature' : IDL.Text,
    'delegation' : IDL.Record({
      'pubkey' : IDL.Text,
      'targets' : IDL.Opt(IDL.Vec(IDL.Text)),
      'expiration' : IDL.Text,
    }),
  });
  const DelegationChain = IDL.Record({
    'publicKey' : IDL.Text,
    'delegations' : IDL.Vec(SignedDelegation),
  });
  
  return IDL.Service({
    'get_delegation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DelegationChain)],
        ['query'],
      ),
    'store_delegation' : IDL.Func([IDL.Text, DelegationChain], [], []),
  });
};

export const init = ({ IDL }) => { return []; };