/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DelegationChain {
  'publicKey' : string,
  'delegations' : Array<SignedDelegation>,
}
export type RegisterResult = { 'ok' : string } |
  { 'err' : string };
export interface SignedDelegation {
  'signature' : string,
  'delegation' : {
    'pubkey' : string,
    'targets' : [] | [Array<string>],
    'expiration' : string,
  },
}
export interface _SERVICE {
  'get_delegation' : ActorMethod<[string], [] | [DelegationChain]>,
  'lookup_code' : ActorMethod<[string], [] | [string]>,
  'register' : ActorMethod<[string, string], RegisterResult>,
  'store_delegation' : ActorMethod<[string, DelegationChain], undefined>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];